/* eslint-disable no-unused-vars */
export enum ErrorMessage {
  ACCOUNT_NOT_EXISTS = 'error.ACCOUNT_NOT_EXISTS',
  ACCOUNT_EXISTS = 'error.ACCOUNT_EXISTS',
  ACCOUNT_IS_BLOCKED = 'error.ACCOUNT_IS_BLOCKED',
  PASSWORD_INCORRECT = 'error.PASSWORD_INCORRECT',
  REFRESH_TOKEN_NOT_EXISTS = 'error.REFRESH_TOKEN_NOT_EXISTS',
}
