export enum ErrorMessage {
  ACCOUNT_NOT_EXISTS = 'error.ACCOUNT_NOT_EXISTS',
  ACCOUNT_EXISTS = 'error.ACCOUNT_EXISTS',
  PASSWORD_INCORRECT = 'error.PASSWORD_INCORRECT',
  REFRESH_TOKEN_NOT_EXISTS = 'error.REFRESH_TOKEN_NOT_EXISTS',
}
