/* eslint-disable no-unused-vars */
export enum EConfiguration {
  PORT = 'PORT',
  JWT_SECRET = 'JWT_SECRET',
  ACCESS_TOKEN_EXPIRES_IN = 'ACCESS_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN_EXPIRES_IN = 'REFRESH_TOKEN_EXPIRES_IN',
  DB_POSTGRESQL_HOST = 'DB_POSTGRESQL_HOST',
  DB_POSTGRESQL_PORT = 'DB_POSTGRESQL_PORT',
  DB_POSTGRESQL_USER = 'DB_POSTGRESQL_USER',
  DB_POSTGRESQL_PASSWORD = 'DB_POSTGRESQL_PASSWORD',
  DB_POSTGRESQL_NAME = 'DB_POSTGRESQL_NAME',
}
